# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

BUILD_DIR = "builds"
EXPORT_DIR = "Releases"

def archive_path
  "#{BUILD_DIR}/keysearch.archive"
end

def app_id
  CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
end

def app_path
  "#{EXPORT_DIR}/Search Key.app"
end

def zip_path
  "#{EXPORT_DIR}/Search Key.zip"
end

def version_number
  get_version_number(target: "Search Key")
end

platform :mac do

  lane :archive do
    xcbuild(
      archive: true,
      archive_path: archive_path,
      scheme: 'keysearch')
  end

  lane :export_archive do
    xcarchive(
      export_archive: true,
      archive_path: archive_path,
      export_path: EXPORT_DIR,
      export_options_plist: {
        destination: 'export',
        method: 'developer-id',
        signing_style: 'automatic',
        team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
      }
    )
  end

  lane :notarize_app do
    notarize(
      package: app_path,
      print_log: "true",
      bundle_id: app_id,
      asc_provider: CredentialsManager::AppfileConfig.try_fetch_value(:asc_provider)
    )
  end

  lane :zip_app do
    zip(
      path: app_path,
      output_path: zip_path,
      verbose: false,
      symlinks: true
    )
  end

  desc "Build"
  lane :build do
    archive
    export_archive
    notarize_app
    zip_app
  end
  
  lane :bump_version do
    increment_build_number
    increment_version_number( bump_type: "minor" )
    commit_version_bump(message: "#{version_number}")
  end

  desc "Upload"
  lane :upload do
    build_mac_app(scheme: "keysearch",
      output_directory: "Releases"
    )
  end
end